### ISSUE TITLE
Error en descarga de indicadores

### ISSUE THREAD

**Issue by DaboinCJ** [EL-BID/Libreria-R-Numeros-para-el-Desarrollo#1]
Presento el siguiente problema desde el mes de Marzo: Al introducir el código de iadbmsearch y iadbstats de la siguiente manera: 
```
install.packages('devtools')
library(devtools)
install_github('El-BID/Libreria-R-Numeros-para-el-Desarrollo')
library(iadbstats)
iadbmsearch(value ='ALL', lang='ES')
iadbstats(country = "COL", frequency = "year", indicatorcode = "ALL")
```
Obtengo el mensaje:
                    ```
 Error: lexical error: invalid char in json text.
                                       An error occurred, please try a
                     (right here) ------^
```
Entiendo que se trata de un error de servidor. ¿Es correcto? de serlo ¿Tienen prevista una solución?
Muchas gracias de antemano.

Saludos,

**Comment by bid-code4dev** [comment]
Hola @DaboinCJ sigues teniendo este problema?

**Comment by martinpaladino** [comment]
Tengo el mismo problema. Aparentemente es del servidor, que regresa un 404 a cualquier solicitud, aún por browser. Por ejemplo: http://api-data.iadb.org/datasitedata?countrycode=abw&frequency=year&languagecode=en&responsetype=xml me da un 404.

**Comment by KyleStr** [comment]
Este problema ha sido resuelto.
